include ../../../make/defines.mk

all:

SHAREDIRT= default_event_script.sl \
	   follow-service.sl

include $(OBJDIR)/make/clean.mk
include $(OBJDIR)/make/install.mk
include $(OBJDIR)/make/uninstall.mk

clean: generalclean
