#!/bin/sh

set -e

# Those using dependency based boot sequencing with sysv-rc and
# installing gfs2-tools before version 2.20081102-1.1 would have wrong
# runlevel symlinks.  Recover from this.
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" le "3.0.2-5" \
   && [ -f /etc/rc2.d/S[0-9][0-9]gfs2-tools ] && [ ! -f /etc/rcS.d/S[0-9][0-9]gfs2-tools ]
then
    update-rc.d -f gfs2-tools remove
fi

#DEBHELPER#
